### ISSUE TITLE
Problems with authentication for Spotify

### ISSUE THREAD

**Issue by lukaszklis** [TheDom/setlist.fm-to-spotify-exporter#3]
When I tried to test #2 locally, I managed to see a Spotify's auth popup, however when tried to login, it threw a 400 error with the following content: `INVALID_CLIENT: Invalid redirect URI`. 
Has something changed in Spotify's API since the last release?

**Comment by TheDom** [comment]
For local development you need to register your own [Spotify app](https://beta.developer.spotify.com/dashboard/applications) and set its redirect URI to the return value of `chrome.identity.getRedirectURL()`. Then change the `clientId` in `background.js` and everything should work.
